version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "bundler" 
    directory: "/" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform" 
    directory: "/" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "build.gradle" 
    directory: "/" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "build.gradle.kts" 
    directory: "/" 
    schedule:
      interval: "weekly"
