name: 'Dependency Review'    

on:
  pull_request:

jobs:
 
  call-workflow:
    uses: gwehrs/demo-repo-test/.github/workflows/dependency-review.yml@v1
    secrets:
        token: ${{ secrets.TOKEN }}

        
    
